package backend;

import java.util.Map;
import java.io.File;
import java.io.Serializable;
import java.util.Collection;
import java.util.HashMap;

/**
 * The root of a tree representing a directory structure.
 */
public class FileNode implements Serializable{

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = -2365147059103012722L;
	
	/** The name of the file or directory this node represents. */
	private String name;
	/** Whether this node represents a file or a directory. */
	private FileType type;

	/** This node's parent. */
	private FileNode parent;
	
	/**
	 * the File type of the file node.
	 */
	private File fileContent; 
	/**
	 * This node's children, mapped from the file names to the nodes. If type is
	 * FileType.FILE, this is null.
	 */
	private Map<String, FileNode> children;

	/**
	 * A node in this tree.
	 *
	 * @param name
	 *            the file
	 * @param parent
	 *            the parent node
	 * @param type
	 *            file or directory
	 * @param file
	 * 			the file of this node
	 */
	public FileNode(String name, FileNode parent, FileType type, File file) {
		this.name = name;
		this.parent = parent;
		this.type = type;
		this.fileContent = file;
		if(this.type == FileType.DIRECTORY) this.children = new HashMap<String, FileNode>();

	}

	/**
	 * Return the name of the file or directory represented by this node.
	 *
	 * @return name of this Node
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the name of the current node
	 *
	 * @param name
	 *            of the file/directory
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Return the child nodes of this node.
	 *
	 * @return the child nodes directly underneath this node.
	 */
	public Collection<FileNode> getChildren() {
		return this.children.values();
	}

	/**
	 * Return this node's parent.
	 * 
	 * @return the parent
	 */
	public FileNode getParent() {
		return parent;
	}

	/**
	 * Set this node's parent to p.
	 * 
	 * @param p
	 *            the parent to set
	 */
	public void setParent(FileNode p) {
		this.parent = p;
	}

	/**
	 * Add childNode, representing a file or directory named name, as a child of
	 * this node.
	 * 
	 * @param name
	 *            the name of the file or directory
	 * @param childNode
	 *            the node to add as a child
	 */
	public void addChild(String name, FileNode childNode) {
		this.children.put(name, childNode);
	}

	/**
	 * Return whether this node represents a directory.
	 * 
	 * @return whether this node represents a directory.
	 */
	public boolean isDirectory() {
		return this.type == FileType.DIRECTORY;
	}
	/**
	 * @return the type
	 */
	public FileType getType() {
		return type;
	}
	
	public String getPath(){
		return this.fileContent.getParent();
	}

	/**
	 * @return the fileContent
	 */
	public File getFile() {
		return fileContent;
	}


}
